Fix several bugs in umount and test syscall
- In build-raspi-kernel.sh
  - Retry umount until copy file to Raspbian disk image completed
- In 03-syscall/test/Makefile
  - Support print PASS or FAIL if testing has passed or not

diff --git a/chapter/03-syscall/test/Makefile b/chapter/03-syscall/test/Makefile
--- a/chapter/03-syscall/test/Makefile
+++ b/chapter/03-syscall/test/Makefile
@@ -13,7 +13,12 @@ all: $(OBJS)
 	$(CC) $^ -o $(EXEC)
 
 check: $(EXEC)
-	./$(EXEC)
+	@./$(EXEC); \
+	if [ $$? -eq 0 ] ; then \
+		echo "PASS."; \
+	else \
+		echo "FAIL."; \
+	fi
 
 clean:
 	rm -f $(OBJS) factorial_ut
